# Generated by Django 4.1.6 on 2023-02-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vending_Machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='codigo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(default='nombre_producto', max_length=20),
        ),
    ]
