# Generated by Django 4.1.6 on 2023-02-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vending_Machine', '0002_rename_producto_producto_codigo_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=6),
        ),
    ]
