# Generated by Django 4.1.4 on 2023-02-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vending_Machine', '0003_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='num_comprados',
            field=models.IntegerField(default=0),
        ),
    ]
